### ISSUE TITLE
token验证失败

### ISSUE THREAD

**Issue by Spencer-star** [LittleNightmare/onebot_Astrologian_FFXIV#4]
使用oicq或者先驱的时候，提示握手失败 1006错误。因为使用ecs服务器，8080端口是占用的，没有找到修改端口的文件位置。
（希望可以改回V1的通过配置文件定义端口和token的方法。。）

**Comment by LittleNightmare** [comment]
嗯。。。应该会有一个.env开头的文件生成在目录下，可以在那里配置端口，这个功能完全是有nonebot2提供了，所以我这里没有具体写
